// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ufZNarOOm5D18WNgfGORLEDHRBlJYAY',
    appId: '1:645529283499:android:e828f408ea1e2f3cc180ee',
    messagingSenderId: '645529283499',
    projectId: 'todoapp-d0868',
    storageBucket: 'todoapp-d0868.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY4hxBU5yRurGuf2T8pUuUo1eTOWfCWxA',
    appId: '1:645529283499:ios:0e439cb0bc334468c180ee',
    messagingSenderId: '645529283499',
    projectId: 'todoapp-d0868',
    storageBucket: 'todoapp-d0868.appspot.com',
    iosClientId:
        '645529283499-08kn8cq2l97i489r21od38fcgsinufag.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY4hxBU5yRurGuf2T8pUuUo1eTOWfCWxA',
    appId: '1:645529283499:ios:0e439cb0bc334468c180ee',
    messagingSenderId: '645529283499',
    projectId: 'todoapp-d0868',
    storageBucket: 'todoapp-d0868.appspot.com',
    iosClientId:
        '645529283499-08kn8cq2l97i489r21od38fcgsinufag.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
